# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-03-12 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=10)),
                ('title', models.CharField(max_length=40)),
                ('text', models.TextField(max_length=400)),
                ('date', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamName', models.CharField(max_length=25, unique=True)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('submitPassword', models.CharField(max_length=20)),
                ('whetherSubmit', models.BooleanField(default=False)),
                ('type', models.CharField(blank=True, max_length=20)),
                ('member1', models.CharField(max_length=12)),
                ('ID1', models.CharField(max_length=13)),
                ('department1', models.CharField(blank=True, max_length=25, null=True)),
                ('member2', models.CharField(blank=True, max_length=12)),
                ('ID2', models.CharField(blank=True, max_length=13)),
                ('department2', models.CharField(blank=True, max_length=25)),
                ('member3', models.CharField(blank=True, max_length=12)),
                ('ID3', models.CharField(blank=True, max_length=13)),
                ('department3', models.CharField(blank=True, max_length=25)),
                ('member4', models.CharField(blank=True, max_length=12)),
                ('ID4', models.CharField(blank=True, max_length=13)),
                ('department4', models.CharField(blank=True, max_length=25)),
                ('member5', models.CharField(blank=True, max_length=12)),
                ('ID5', models.CharField(blank=True, max_length=13)),
                ('department5', models.CharField(blank=True, max_length=25)),
                ('URL', models.URLField(blank=True, max_length=100)),
                ('sharePassword', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, verbose_name='\u6bd4\u8d5b\u7c7b\u522b')),
                ('signup_start', models.CharField(blank=True, max_length=20, verbose_name='\u62a5\u540d\u5f00\u59cb\u65f6\u95f4')),
                ('signup_end', models.CharField(blank=True, max_length=20, verbose_name='\u62a5\u540d\u7ed3\u675f\u65f6\u95f4')),
                ('submit_start', models.CharField(blank=True, max_length=20, verbose_name='\u63d0\u4ea4\u4f5c\u54c1\u5f00\u59cb\u65f6\u95f4')),
                ('submit_end', models.CharField(blank=True, max_length=20, verbose_name='\u63d0\u4ea4\u4f5c\u54c1\u7ed3\u675f\u65f6\u95f4')),
            ],
        ),
    ]
