# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-25 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamName', models.CharField(max_length=25, unique=True)),
                ('phone', models.IntegerField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('teamID', models.IntegerField()),
                ('submitPassword', models.CharField(max_length=20)),
                ('whetherSubmit', models.BooleanField(default=False)),
                ('member1', models.CharField(max_length=12)),
                ('ID1', models.IntegerField(max_length=13)),
                ('department1', models.CharField(max_length=25)),
                ('member2', models.CharField(blank=True, max_length=12)),
                ('ID2', models.IntegerField(blank=True, max_length=13)),
                ('department2', models.CharField(blank=True, max_length=25)),
                ('member3', models.CharField(blank=True, max_length=12)),
                ('ID3', models.IntegerField(blank=True, max_length=13)),
                ('department3', models.CharField(blank=True, max_length=25)),
                ('member4', models.CharField(blank=True, max_length=12)),
                ('ID4', models.IntegerField(blank=True, max_length=13)),
                ('department4', models.CharField(blank=True, max_length=25)),
                ('member5', models.CharField(blank=True, max_length=12)),
                ('ID5', models.IntegerField(blank=True, max_length=13)),
                ('department5', models.CharField(blank=True, max_length=25)),
            ],
        ),
    ]
