# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-25 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='URL',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='sharePassword',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='team',
            name='ID1',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='team',
            name='ID2',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='team',
            name='ID3',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='team',
            name='ID4',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='team',
            name='ID5',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='team',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
